wandb_version: 1

Trainer.total_steps:
  value: 50000
vgg_like.base_filters:
  value: 113
vgg_like.dense_units:
  value: 24
vgg_like.dropout_rate:
  value: 0.13467588424015792
vgg_like.n_blocks:
  value: 5
