wandb_version: 1

Trainer.total_steps:
  value: 50000
vgg_like.base_filters:
  value: 50
vgg_like.dense_units:
  value: 18
vgg_like.dropout_rate:
  value: 0.31850772698697594
vgg_like.n_blocks:
  value: 5
