wandb_version: 1

Trainer.total_steps:
  value: 50000
vgg_like.base_filters:
  value: 15
vgg_like.dense_units:
  value: 61
vgg_like.dropout_rate:
  value: 0.3264293808336802
vgg_like.n_blocks:
  value: 6
