wandb_version: 1

Trainer.total_steps:
  value: 50000
vgg_like.base_filters:
  value: 35
vgg_like.dense_units:
  value: 49
vgg_like.dropout_rate:
  value: 0.6933021110876492
vgg_like.n_blocks:
  value: 4
