wandb_version: 1

Trainer.total_steps:
  value: 50000
vgg_like.base_filters:
  value: 34
vgg_like.dense_units:
  value: 40
vgg_like.dropout_rate:
  value: 0.8794030541550736
vgg_like.n_blocks:
  value: 5
